CREATE DATABASE MDB ;
USE MDB;
CREATE TABLE JobDepartment (
    Job_ID INT PRIMARY KEY,
    jobdept VARCHAR(50),
    name VARCHAR(100),
    description TEXT,
    salaryrange VARCHAR(50)
);

SELECT * FROM JOBDEPARTMENT;

-- TABLE 2
CREATE TABLE SalaryBonus (
    salary_ID INT PRIMARY KEY,
    Job_ID INT,
    amount DECIMAL(10,2),
    annual DECIMAL(10,2),
    bonus DECIMAL(10,2),
    CONSTRAINT fk_salary_job FOREIGN KEY (job_ID) REFERENCES JobDepartment(Job_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

SELECT * FROM SALARYBONUS;

-- Table 3: Employee
CREATE TABLE Employee (
    emp_ID INT PRIMARY KEY,
    firstname VARCHAR(50),
    lastname VARCHAR(50),
    gender VARCHAR(10),
    age INT,
    contact_add VARCHAR(100),
    emp_email VARCHAR(100) UNIQUE,
    emp_pass VARCHAR(50),
    Job_ID INT,
    CONSTRAINT fk_employee_job FOREIGN KEY (Job_ID)
        REFERENCES JobDepartment(Job_ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

SELECT * FROM EMPLOYEE;

-- Table 4: Qualification
CREATE TABLE Qualification (
    QualID INT PRIMARY KEY,
    Emp_ID INT,
    Position VARCHAR(50),
    Requirements VARCHAR(255),
    Date_In DATE,
    CONSTRAINT fk_qualification_emp FOREIGN KEY (Emp_ID)
        REFERENCES Employee(emp_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

SELECT * FROM QUALIFICATION;

-- Table 5: Leaves
CREATE TABLE Leaves (
    leave_ID INT PRIMARY KEY,
    emp_ID INT,
    date DATE,
    reason TEXT,
    CONSTRAINT fk_leave_emp FOREIGN KEY (emp_ID) REFERENCES Employee(emp_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

SELECT * FROM LEAVES;

-- Table 6: Payroll
CREATE TABLE Payroll (
    payroll_ID INT PRIMARY KEY,
    emp_ID INT,
    job_ID INT,
    salary_ID INT,
    leave_ID INT,
    date DATE,
    report TEXT,
    total_amount DECIMAL(10,2),
    CONSTRAINT fk_payroll_emp FOREIGN KEY (emp_ID) REFERENCES Employee(emp_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payroll_job FOREIGN KEY (job_ID) REFERENCES JobDepartment(job_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payroll_salary FOREIGN KEY (salary_ID) REFERENCES SalaryBonus(salary_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_payroll_leave FOREIGN KEY (leave_ID) REFERENCES Leaves(leave_ID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

SELECT * FROM JOBDEPARTMENT;
SELECT * FROM SALARYBONUS;
SELECT * FROM EMPLOYEE;
SELECT * FROM QUALIFICATION;
SELECT * FROM LEAVES;
SELECT * FROM PAYROLL;


-- 1. EMPLOYEE INSIGHTS
-- 1. HOW MANY UNIQUE EMPLOYEE ARE CUNRRENTLY IN THE SYSTEM?

SELECT COUNT(DISTINCT EMP_ID) AS TOTAL_EMPLOYEES
FROM EMPLOYEE;

-- 2.WHICH DEPARTMNET HAVE THE HIGHEST NUMBER OF EMPLOYEES?
SELECT JD.JOBDEPT,
COUNT(E.EMP_ID) AS EMPLOYEE_COUNT
FROM EMPLOYEE E
JOIN JOBDEPARTMENT JD
ON E.JOB_ID = JD.JOB_ID
GROUP BY JD.JOBDEPT
ORDER BY EMPLOYEE_COUNT DESC;

-- 3.WHAT IS THE AVERAGE SALARY OF EMPLOYEES BY DEPARTMENT?
SELECT JD.JOBDEPT,
	   AVG(SB.AMOUNT) AS AVERAGE_SALARY
FROM EMPLOYEE E
JOIN JOBDEPARTMENT JD
ON E.JOB_ID = JD.JOB_ID
JOIN SALARYBONUS SB
ON JD.JOB_ID = SB.JOB_ID
GROUP BY JD.JOBDEPT;

-- 4. WHO ARE THE TOP 5 HIGHEST_PAID EMPLOYEES?
SELECT E.EMP_ID,
	   E.FIRSTNAME,
       E.LASTNAME,
       JD.JOBDEPT,
       SB.AMOUNT AS SALARY
FROM EMPLOYEE E
JOIN JOBDEPARTMENT JD
ON E.JOB_ID = JD.JOB_ID
JOIN SALARYBONUS SB
ON JD.JOB_ID = SB.JOB_ID
ORDER BY SB.AMOUNT DESC
LIMIT 5;

-- 5.what is the total salary expemditure across the company?
SELECT SUM(AMOUNT) AS TOTAL_SALARY_EXPENDITURE
FROM SALARYBONUS;

-- 2.JOB ROLE AND DEPARTMENT ANALYSIS
-- 1.HOW MANY DIFFERENT JOB EXIST IN EACH DEPARTMENT?
SELECT JOBDEPT,
COUNT(NAME) AS TOTAL_JOB_ROLES
FROM JOBDEPARTMENT
GROUP BY JOBDEPT;

-- 2.WHAT IS THE AVERAGE SALARY PER DEPARTMENT?
SELECT JD.JOBDEPT,
AVG(SB.AMOUNT) AS AVERAGE_SALARY
FROM JOBDEPARTMENT JD
JOIN SALARYBONUS SB
ON JD.JOB_ID = SB.JOB_ID
GROUP BY JD.JOBDEPT;

-- 3.WHICH JOB ROLES OFFER THE HIGEST SALARY?
SELECT JD.NAME AS JOB_ROLE,
       JD.JOBDEPT,
       SB.AMOUNT
FROM JOBDEPARTMENT JD
JOIN SALARYBONUS SB
ON JD.JOB_ID = SB.JOB_ID
ORDER BY SB.AMOUNT DESC
LIMIT 1;

-- 4.WHICH DEPARTMENT HAS THE HIGHEST TOTAL SALARY ALLOCATION?
SELECT JD.JOBDEPT,
       SUM(SB.AMOUNT) AS TOTAL_SALARY_ALLOCATION
FROM JOBDEPARTMENT JD
JOIN SALARYBONUS SB
ON JD.JOB_ID = SB.JOB_ID
GROUP BY JD.JOBDEPT
ORDER BY TOTAL_SALARY_ALLOCATION DESC;

-- 3.QUALIFICATION AND SKILLS ANALYSIS
-- 1.HOW MANY EMPLOYUEES HAVE AT LEAST ONE QUALIFICATION LISTED?
SELECT COUNT(DISTINCT EMP_ID) AS TOTAL_EMPLOYEES_WITH_QUALIFICATIONS
FROM QUALIFICATION;

-- 2. WHICH POSITION REQUIRE THE MOST QUALIFICATIONS?
SELECT Position,
       COUNT(Requirements) AS total_qualifications
FROM Qualification
GROUP BY Position
ORDER BY total_qualifications DESC;

-- 3.WHICH EMPLOYEES HAVE THE HIGHEST NUMBER OF QUALIFICATIONS?
SELECT E.EMP_ID,
	   E.FIRSTNAME,
       E.LASTNAME,
       COUNT(Q.QUALID) AS TOTAL_QUALIFICATIONS
FROM EMPLOYEE E
JOIN QUALIFICATION Q
ON E.EMP_ID = Q.EMP_ID
GROUP BY E.EMP_ID,E.FIRSTNAME,E.LASTNAME
ORDER BY TOTAL_QUALIFICATIONS DESC;

-- 3. LEAVE AND ABSENECE PATTERNS
-- 1.WHICH YEAR HAD THE MOST EMPLOYEES TAKING LEAVES?
SELECT YEAR(DATE) AS LEAVE_YEAR,
COUNT(DISTINCT EMP_ID) AS TOTAL_EMPLOYEES
FROM LEAVES
GROUP BY YEAR(DATE)
ORDER BY TOTAL_EMPLOYEES DESC;
--     OR
SELECT e.emp_ID,
       e.firstname,
       e.lastname,
       COUNT(l.leave_ID) AS total_leaves
FROM Employee e
JOIN Leaves l
ON e.emp_ID = l.emp_ID
GROUP BY e.emp_ID, e.firstname, e.lastname
ORDER BY total_leaves DESC
LIMIT 1;

-- 2.WHAT IS THE AVERAGE NUMBER OF LEAVE DAYS TAKEN BY ITS EMPLOYEES PER DEPARTMENT?
SELECT 
    JD.JOBDEPT,
    COUNT(L.LEAVE_ID) / COUNT(DISTINCT E.EMP_ID) AS AVERAGE_LEAVE_DAYS
FROM EMPLOYEE E
JOIN JOBDEPARTMENT JD
ON E.JOB_ID = JD.JOB_ID
LEFT JOIN LEAVES L
ON E.EMP_ID = L.EMP_ID
GROUP BY JD.JOBDEPT;

-- 3.WHICH EMPLOYEES HAVE TAKEN THE MOST LEAVES?
SELECT 
    E.EMP_ID,
    E.FIRSTNAME,
    E.LASTNAME,
    COUNT(L.LEAVE_ID) AS TOTAL_LEAVES
FROM EMPLOYEE E
JOIN LEAVES L
ON E.EMP_ID = L.EMP_ID
GROUP BY E.EMP_ID, E.FIRSTNAME, E.LASTNAME
HAVING COUNT(L.LEAVE_ID) = (
    SELECT MAX(LEAVE_COUNT)
    FROM (
        SELECT COUNT(LEAVE_ID) AS LEAVE_COUNT
        FROM LEAVES
        GROUP BY EMP_ID
    ) AS TEMP
);

-- 4. WHAT IS THE TOTAL NUMBER OF LEAVE DAYS TAKLEN COMAPANY-WIDE?
SELECT COUNT(*) AS TOTAL_LEAVE_DAYS
FROM LEAVES;

-- 5.HOW DO LEAVE DAYS CORRELATE WITH PAYROLL AMOUNTS?
SELECT e.emp_ID,
       e.firstname,
       COUNT(l.leave_ID) AS total_leaves,
       AVG(p.total_amount) AS average_payroll
FROM Employee e
LEFT JOIN Leaves l
ON e.emp_ID = l.emp_ID
LEFT JOIN Payroll p
ON e.emp_ID = p.emp_ID
GROUP BY e.emp_ID, e.firstname
ORDER BY total_leaves DESC;

-- 5.PAYROLL AND COMPENSATION ANALYSIS
-- 1.WHAT IS THE TOTAL MONTHLY PAYROLL PROCESSED?
SELECT YEAR(DATE) AS PAYROLL_YEAR,
MONTH(DATE) AS PAYROLL_MONTH,
SUM(TOTAL_AMOUNT) AS TOTAL_MONTHLY_PAYROLL
FROM PAYROLL
GROUP BY YEAR(DATE),MONTH(DATE)
ORDER BY PAYROLL_YEAR,PAYROLL_MONTH;

-- 2.WHAT IS THE AVERAGE BONUS GIVEN PER DEPARTMENT?
SELECT JD.JOBDEPT,
AVG(SB.BONUS) AS AVERAGE_BONUS
FROM JOBDEPARTMENT JD
JOIN SALARYBONUS SB
ON JD.JOB_ID =SB.JOB_ID
GROUP BY JD.JOBDEPT;

-- 3.WHICH DEPARTMENT RECEIVES THE HIGHEST TOTAL BONUSES?
SELECT jd.jobdept,
       SUM(sb.bonus) AS total_bonus
FROM JobDepartment jd
JOIN SalaryBonus sb
ON jd.Job_ID = sb.Job_ID
GROUP BY jd.jobdept
ORDER BY total_bonus DESC;

-- 4.WHAT IS THE AVERAGE VALUE OF TOTAL_AMOUNT AFTER CONSIDERING LEAVE DEDUCTIONS?
SELECT AVG(TOTAL_AMOUNT) AS AVERAGE_PAYROLL_AFTER_DEDUCTIONS
FROM PAYROLL;

